Repository LearnsMate/LearnsMateBackend, pull requests merged in 2024-12, with the labels that each got.

#304 ♻️코드 수정: importTargetCouponFromExcel 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponFindResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponExcelService.java
Labels: fix

#303 ✨ 기능 수정 : RedisConfig 수정
  .github/workflows/deploy.yml
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/AppConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/BatchConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/RedisConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: fix

#306 ✨기능 추가: CoolSmsService -> sendSms 추가
  LearnsMate/build.gradle
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/EmailService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/entity/Campaign.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestRegisterCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseRegisterCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CoolSmsService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/CoolSmsConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java
Labels: enhancement

#307 ♻️코드 수정: campaignSendFlag 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/FindAllCampaignsDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/FindCampaignDetailDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignStudentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestFindCampaignByFilterVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestRegisterCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseEditCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignByFilterVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignDetailVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseRegisterCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
Labels: fix

#308 ♻️코드 수정: getApprovalProcessByLectureCode List로 반환
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/controller/ContractStatusController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/repository/ContractStatusRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/service/ContractStatusService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/service/ContractStatusServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
Labels: fix

#310 ✨기능 추가: MemberController -> getMemberCount 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/MemberCountResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseMemberCountVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: enhancement

#314 결제 내역 필터링 기능, 필요 컬럼 선택 기능, 엑셀 다운로드 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/dto/PaymentFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/PaymentFilterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/repository/CustomPaymentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/repository/CustomPaymentRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: enhancement, fix

#316 ✨기능 추가/수정: 쿠폰 등록 유형 필터 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/CouponFilterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponFindResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
Labels: enhancement

#320 ✨ 기능 추가 : 쿠키에서 refreshToken을 추출 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/TokenController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/entity/CustomUserDetails.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/WebConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: bug, enhancement

#321 ♻️ 코드 수정 : 쿠폰 등록 시 강의 필터링 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
Labels: enhancement

#322 ♻️코드 수정: 쿠폰 활성화 필터 적용 안되는 현상 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java
Labels: fix

#315 ✨ 기능 추가 : deploy.yml 에 cool-sms 추가
  .github/workflows/deploy.yml
Labels: enhancement

#323 ♻️코드 수정: 쿠폰 전체 조회 시 생성일 기준 내림차순 정렬 적용
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java
Labels: fix

#324 ♻️ 코드 수정: 프론트엔드 배포 연동
  .github/workflows/deploy.yml
  LearnsMate/build.gradle
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/TokenController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/RedisService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/mapper/BlacklistMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/client/controller/ClientController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/client/service/ClientService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/RedisConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/WebConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/service/ContractStatusServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/controller/CouponByCampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/AuthenticationFilter.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/JwtFilter.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/JwtUtil.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCAiService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/mapper/VOCAnswerMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
Labels: enhancement

#325 ♻️ 코드 수정: websecurity cors 문제 해결
  .github/workflows/deploy.yml
  LearnsMate/src/main/java/intbyte4/learnsmate/client/controller/ClientController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseClientFindLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/domain/entity/LoginHistory.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/service/LoginHistoryService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestLoginVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestLogoutVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseLoginVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/JwtFilter.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/request/RequestSaveVOCVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VOCMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
Labels: fix

#327 ✨ 기능 추가 / 수정: Student, tutor, blacklist sort 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/repository/ReportRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/service/ReportService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
Labels: enhancement

#328 ✨기능 추가/수정: 강의 정렬기능 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
Labels: bug

#329 ♻️코드 수정: 캠페인 발송 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/CustomIssueCouponRepositoryImpl.java
Labels: fix

#330 ♻️ 코드 수정: 직원이 강사 쿠폰 수정, 삭제 시 에러 코드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
Labels: enhancement

#333 ✨기능 추가: payment, voc 컬럼 정렬 적용
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/repository/CustomPaymentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/repository/CustomPaymentRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
Labels: enhancement

#335 ✨기능 추가/수정: 쿠폰, 발급쿠폰 필터링x 정렬o 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/batch/CampaignIssueCouponProcessor.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/batch/CampaignIssueCouponReader.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/batch/CampaignIssueCouponWriter.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestRegisterCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/CustomIssueCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/CustomIssueCouponRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponFacade.java
Labels: enhancement

#336 ✨기능 추가/수정: 캠페인 템플릿 필터링, 컬럼정렬 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/controller/CampaignTemplateController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
Labels: enhancement

#337 ✨기능 추가, 수정: build.gradle spotbugs 추가
  LearnsMate/build.gradle
Labels: enhancement

#339 ✨기능 추가: CampaignService -> findAllCampaignListBySort, findCampaignListByFilterAndSort 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
Labels: fix

#340 ♻️ 코드 수정 : 쿠폰 필터링 시 데이터 형태 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/CouponFilterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponFindResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java
Labels: fix

#341 ✨기능 추가/수정: 회원 정렬 없는 필터링 기능 복원
  LearnsMate/src/main/java/intbyte4/learnsmate/client/service/ClientService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: bug, enhancement

#343 ♻️ 코드 수정 : 삭제가 되지 않은 쿠폰만 조회
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
Labels: fix

#345 ♻️코드 수정: 캠페인 템플릿 엑셀 다운로드 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
Labels: fix

#346 ♻️코드 수정: CouponRepository 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java
Labels: fix

#348 ♻️코드 수정: CampaignServiceImpl 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
Labels: fix

#349 ♻️ 코드 수정 : 강의 endYear, endMonth 일부 필터링 오류 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
Labels: fix

#350 ♻️ 코드 수정 : 문자가 안 보내지는 오류 수정을 위해 커밋
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java
Labels: fix
