Repository LearnsMate/LearnsMateBackend, pull requests merged in 2024-11, with the labels that each got.

#5 ✨ 기능 추가: Campaign 기본 세팅 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/entity/Campaign.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
Labels: enhancement

#11 ✨ 코드 추가 : 캠페인 템플릿 기능 개발 전 기본 세팅 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/controller/CampaignTemplateController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/CampaignTemplate.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/repository/CampaignTemplateRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignServiceImpl.java
Labels: enhancement

#13 feat(#12): Member 기본 세팅
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/MemberType.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/entity/Member.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/MemberRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: enhancement

#15 feat(#14): Coupon 기본 세팅
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
Labels: enhancement

#21 ✨ 기능 추가 : Lecture Entity 및 DTO 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/controller/CommentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/domain/dto/CommentDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/domain/entity/Comment.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/repository/CommentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/service/CommentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/service/CommentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/controller/ContractProcessController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/domain/dto/ContractProcessDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/domain/entity/ContractProcess.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/repository/ContractProcessRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/service/ContractProcessService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/service/ContractProcessServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/Lecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/LectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecturebystudent/domain/dto/LectureByStudentDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecturebystudent/domain/entity/LectureByStudent.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecturebystudent/repository/LectureByStudentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecturebystudent/service/LectureByStudentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecturebystudent/service/LectureByStudentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecturevideobystudent/domain/dto/LectureVideoByStudentDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecturevideobystudent/domain/entity/LectureVideoByStudent.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecturevideobystudent/repository/LectureVideoByStudentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecturevideobystudent/service/LectureVideoByStudentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecturevideobystudent/service/LectureVideoByStudentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/dto/PaymentDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/entity/Payment.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/repository/PaymentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/videobylecture/controller/VideoByLectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/videobylecture/domain/dto/VideoByLectureDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/videobylecture/domain/entity/VideoByLecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/videobylecture/repository/VideoByLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/videobylecture/service/VideoByLectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/videobylecture/service/VideoByLectureServiceImpl.java
Labels: enhancement

#22 ✨ 기능 추가 : Admin Entity 및 DTO 관련 Service, Repository 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/dto/AdminDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/entity/Admin.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/repository/AdminRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminServiceImpl.java
Labels: enhancement

#23 Feature/campaign template (#2) : 캠페인 템플릿 등록 코드 추가 및 Admin 관련 메소드 추가 + swagger 적용
  LearnsMate/build.gradle
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/dto/AdminDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/entity/Admin.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/controller/CampaignTemplateController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/CampaignTemplate.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/dto/CampaignTemplateDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/vo/request/RequestRegisterTemplateVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/vo/response/ResponseRegisterTemplateVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/repository/CampaignTemplateRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SwaggerConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
Labels: enhancement

#28 ✨ 기능 추가: 캠페인 등록 기능을 위한 registCampaign 메서드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/entity/Campaign.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/entity/CampaignTypeEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
Labels: enhancement

#29 ✨ 기능 추가 / 수정: Blacklist 기본 세팅 완료
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/dto/BlacklistDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/entity/Blacklist.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/request/RequestBlacklistVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseBlacklistVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
Labels: enhancement

#30 ✨ 기능 추가 / 수정: Mapper class 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/common/mapper/GenericMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/mapper/MemberMapper.java
Labels: enhancement

#31 ✨ 기능 추가: RequestInsertCampaignVO,ResponseInsertCampaignVO 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestInsertCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseInsertCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
Labels: enhancement

#34 MemberMapper 생성
  LearnsMate/src/main/java/intbyte4/learnsmate/common/mapper/GenericMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/mapper/MemberMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/entity/Member.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestSaveMemberVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseFindMemberVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: bug, enhancement

#37 ✨ 기능 추가: CampaignService - 캠페인 수정 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/entity/Campaign.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestInsertCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestRegisterCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseEditCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseInsertCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseRegisterCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
Labels: enhancement

#38 feat(#36 ): 캠페인 삭제 API 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/controller/CampaignTemplateController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateServiceImpl.java
Labels: enhancement

#39 ✨ 기능 추가 : LectureSpecifications 동적 필터링 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/Lecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/specification/LectureSpecifications.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/EditLectureInfoVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/enums/LectureCategory.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/enums/LectureLevel.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/LectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
Labels: enhancement

#43 feat(#42): 캠페인 템플릿 컨트롤러 - 전체 조회 기능 추가 및 Operation 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/controller/CampaignTemplateController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/vo/response/ResponseFindTemplateVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/mapper/CampaignTemplateMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateServiceImpl.java
Labels: enhancement

#47 ✨ 기능 추가: CampaignService -> 캠페인 취소 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestRegisterCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseEditCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseRegisterCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
Labels: enhancement

#46 feat(#44 ): 캠페인 템플릿 단 건 조회 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/controller/CampaignTemplateController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/CampaignTemplate.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/dto/CampaignTemplateDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/vo/request/RequestEditTemplateVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/vo/request/RequestRegisterTemplateVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/vo/response/ResponseEditTemplateVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/vo/response/ResponseFindTemplateVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/vo/response/ResponseRegisterTemplateVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/mapper/CampaignTemplateMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
Labels: enhancement

#52 ✨ 기능 추가: CampaignService -> 캠페인 전체 조회 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/entity/Campaign.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
Labels: enhancement

#51 blacklist 조회 기능(학생, 강사 구분) 및 도메인 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindReportVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/mapper/BlacklistMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
Labels: enhancement

#54 ✨ 기능 추가: CampaignService -> 캠페인 단건 조회 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestFindCampaignByCampaignCodeVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
Labels: enhancement

#55 ✨ 기능 추가 / 수정: MemberService -> 강사코드로 강사명 찾아오는 서비스 메서드 작성
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/controller/ReportController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/repository/ReportRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/service/ReportService.java
Labels: enhancement

#58 feat(#56, #57 ): VOC 전체 조회, 단 건 조회 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VocController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/Voc.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/dto/VocDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/response/ResponseFindVocVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VocMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VocRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VocService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VocServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/domain/VocCategory.java
Labels: enhancement

#66 Feature/voc : 엔티티 변환 추가 및 VOC 답변에서 사용하기 위한 VOC카테고리 서비스 코드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VocMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VocServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/domain/dto/VocCategoryDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/repository/VocCategoryRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VocCategoryService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VocCategoryServiceImpl.java
Labels: enhancement

#65 feat(#7) 쿠폰 등록 기능
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/CouponRegisterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponRegisterResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
Labels: enhancement

#67 feat(#59 ): VOC 답변 등록 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/controller/VocAnswerController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/VocAnswer.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/dto/VocAnswerDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestRegisterVocAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseRegisterVocAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/mapper/VocAnswerMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/repository/VocAnswerRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VocAnswerService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VocAnswerServiceImpl.java
Labels: enhancement

#69 feat(#68 ): Member 학생코드로 Member 조회 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VocAnswerServiceImpl.java
Labels: enhancement

#70 feat(#60 ): VOC 답변 수정 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/response/ResponseFindVocVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/controller/VOCAnswerController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/controller/VocAnswerController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/VOCAnswer.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/dto/VOCAnswerDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestEditVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestRegisterVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseEditVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseRegisterVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/mapper/VOCAnswerMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/mapper/VocAnswerMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/repository/VOCAnswerRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VocAnswerService.java
Labels: enhancement

#78 feat(#77): VOC 답변 등록 시 VOC의 답변 현황 True로 변경 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/VOCAnswer.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestEditVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestRegisterVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseEditVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseFindVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseRegisterVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
Labels: enhancement

#79 ♻️ 코드 수정: 단 건 조회 controller 메서드명 수정, table 어노테이션 주석 제거
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java
Labels: enhancement

#82 feat(#81): 쿠폰 카테고리 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/domain/CouponCategory.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/domain/dto/CouponCategoryDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/repository/CouponCategoryRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/service/CouponCategoryService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/service/CouponCategoryServiceImpl.java
Labels: enhancement

#83 ✨ 기능 추가 / 수정: 신고 5회 이상 당한 사람 예비 블랙리스트로 보여주는 로직 구현
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindReservedStudentBlacklistVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindReservedTutorBlacklistVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/mapper/BlacklistMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/domain/dto/ReportedMemberDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/repository/ReportRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/service/ReportService.java
Labels: enhancement

#85 ✨ 기능 추가 / 수정: 회원정보 수정, 삭제 메서드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/entity/Member.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestEditMemberVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: duplicate, enhancement

#87 feat(#86 ): 발급 쿠폰 등록 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/IssueCoupon.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/dto/IssueCouponDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/vo/request/IssueCouponRegisterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/vo/response/IssueCouponRegisterResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/mapper/IssueCouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
Labels: enhancement

#90 ✨ 기능 추가 / 수정: 학생 단건 조회, 강사 단건 조회 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: enhancement

#89 캠페인 템플릿 코드 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/CampaignTemplate.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/vo/request/RequestRegisterTemplateVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/vo/response/ResponseEditTemplateVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/mapper/CampaignTemplateMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
Labels: enhancement

#95 ✨ 기능 추가 / 수정: Comment 전체, 단건 조회 메서드 구현
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/controller/CommentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/domain/vo/request/ResponseFindCommentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/mapper/CommentMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/service/CommentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/service/CommentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
Labels: enhancement

#98 ♻️ 코드 수정: 자료형으로 인한 오류 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestFindCampaignCouponVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/CouponRegisterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponFindResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponRegisterResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
Labels: bug

#101 ✨ 기능 수정: CampaignService -> editCampaign 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignCouponVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignStudentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/mapper/CouponByCampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/repository/CouponByCampaignRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/service/CouponByCampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/service/CouponByCampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/userpercampaign/repository/UserPerCampaignRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/userpercampaign/service/UserPerCampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/userpercampaign/service/UserPerCampaignServiceImpl.java
Labels: enhancement, fix

#102 ✨ 기능 추가 / 수정: 학생, 강사 예비 블랙리스트 단건 조회 메서드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/dto/BlacklistReportCommentDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindReservedBlacklistOneVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/mapper/BlacklistMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/controller/CommentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/repository/ReportRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/service/ReportService.java
Labels: enhancement

#105 ♻️ 코드 수정: CouponByCampaignDTO -> 컬럼명 수정, 타입 변경
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignCouponVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/domain/dto/CouponByCampaignDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/mapper/CouponByCampaignMapper.java
Labels: fix

#109 ✨ 기능 추가 : AdminController 직원 정보 수정 Controller 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/dto/AdminDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/entity/Admin.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/request/RequestEditAdminVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/response/ResponseEditAdminVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/response/ResponseFindAdminVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/mapper/AdminMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
Labels: enhancement

#108 ✨ 기능 추가 / 수정: 학생, 강사 블랙리스트 단건 조회 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
Labels: duplicate, enhancement

#110 ✨ 기능 추가 :JsonNaming 스네이크 케이스로 변환 기능 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/request/RequestEditAdminVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/response/ResponseEditAdminVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/response/ResponseFindAdminVO.java
Labels: enhancement, fix

#112 ✨ 기능 추가 / 수정: LoginHistory mvc 기본 세팅 구현
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/controller/LoginHistoryController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/domain/dto/LoginHistoryDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/domain/entity/LoginHistory.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/mapper/LoginHistoryMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/repository/LoginHistoryRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/service/LoginHistoryService.java
Labels: enhancement, good first issue

#113 ♻️ 코드 수정: CampaignController -> @RequestBody 중복 삭제
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestRegisterCampaignVO.java
Labels: fix

#115 ✨ 기능 추가: CampaignService -> findCampaignsByType 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignByTypeVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
Labels: enhancement

#118 ✨ 기능 추가 / 수정: 로그인 내역 조회, 추가, 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecturebystudent/service/LectureByStudentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/controller/LoginHistoryController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/domain/entity/LoginHistory.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/domain/vo/request/RequestSaveLoginHistoryVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/domain/vo/response/ResponseFindLoginHistoryVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/mapper/LoginHistoryMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/repository/LoginHistoryRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/service/LoginHistoryService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: enhancement

#121 feat(#120 ): 강사의 강의 별 조회 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/controller/CouponByLectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/domain/CouponByLecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/domain/dto/CouponByLectureDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/domain/vo/response/CouponByLectureFindResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/mapper/CouponByLectureMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/repository/CouponByLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/service/CouponByLectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/service/CouponByLectureServiceImpl.java
Labels: enhancement

#122 ♻️ 코드 수정 : 강의 별 쿠폰 조회 쿼리 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/repository/CouponByLectureRepository.java
Labels: fix

#123 feat(#6): 쿠폰 조회
  LearnsMate/build.gradle
  LearnsMate/src/main/java/intbyte4/learnsmate/config/QuerydslConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/CouponFilterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponFilterResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
Labels: enhancement

#126 feat(#7): 직원 쿠폰 등록
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/TutorCouponRegisterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
Labels: enhancement

#128 feat(#127): 직원 쿠폰 등록 기능
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/AdminCouponRegisterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
Labels: enhancement

#130 feat(#129): 직원 쿠폰 수정 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/AdminCouponEditRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/CouponRegisterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/AdminCouponEditResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
Labels: enhancement

#131 ✨ 기능 추가 / 수정: 선호 주제 리스트 조회, 등록 메서드, 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/controller/PreferredTopicsController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/dto/PreferredTopicsDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/entity/PreferredTopics.java
  LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/vo/request/RequestSavePreferredHistoryVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/vo/response/ResponseFindPreferredTopicsVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/mapper/PreferredTopicsMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/repository/PreferredTopicsRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/service/PreferredTopicsService.java
Labels: enhancement, good first issue

#132 직원 쿠폰 수정 시 직원 validation 코드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
Labels: fix

#134 feat(#133): 직원 코드 삭제 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
Labels: enhancement

#135 ✨ 기능 수정 : registerLecture Service 기능 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/controller/ContractProcessController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/domain/vo/request/ResponseRegisterContractProcessVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/domain/vo/response/RequestRegisterContractProcessVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/domain/vo/response/ResponseFindContractProcessVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/mapper/ContractProcessMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/repository/ContractProcessRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/service/ContractProcessService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/service/ContractProcessServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: enhancement

#137 특정 고객의 VOC에 대해 미답변, 답변에 따라 조회할 수 있게 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
Labels: enhancement

#139 ✨ 기능 추가 : GptConfig 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/config/GptConfig.java
Labels: enhancement

#141 feat(#7, #140): 쿠폰 삭제 (강사), 강사 쿠폰 활성화, 비활성화 상태 변경
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/TutorCouponEditRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/TutorCouponEditResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
Labels: enhancement

#142 ✨ 기능 추가 / 수정: 특정 강의별 강의 카테고리 코드로 조회하는 메서드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/service/ContractProcessServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/Lecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/request/RequestEditLectureInfoVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/request/RequestRegisterLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseEditLectureInfoVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseFindLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseRegisterLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseRemoveLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/controller/LectureCategoryByLectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/domain/dto/LectureCategoryByLectureDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/domain/dto/OneLectureCategoryListDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/domain/entity/LectureCategoryByLecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/domain/vo/response/ResponseFindLectureCategoryByLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/mapper/LectureCategoryByLectureMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/controller/LoginHistoryController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/controller/PreferredTopicsController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/video_by_lecture/service/VideoByLectureServiceImpl.java
Labels: enhancement

#143 ✨ 기능 수정 : Lecture 기능 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/video_by_lecture/service/VideoByLectureServiceImpl.java
Labels: bug

#146 엑셀 다운로드/업로드를 위한 의존성 추가, 컨트롤러 서비스 추가
  LearnsMate/build.gradle
  LearnsMate/src/main/java/intbyte4/learnsmate/excel/controller/ExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/excel/service/ExcelService.java
Labels: enhancement

#147 발급 쿠폰, 학생 별 순환참조 해결을 위한 퍼사드 패턴 적용
  LearnsMate/src/main/java/intbyte4/learnsmate/facade/MemberCouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
Labels: enhancement, fix

#148 발급 쿠폰 쿼리 메소드 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/facade/MemberCouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
Labels: fix

#153 ✨ 기능 추가 / 수정: 멤버 상세 조회 메서드 이동 및 수정 및 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/FindSingleMemberDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberIssueCouponDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberVOCDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseFindMemberDetailVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: bug, enhancement

#152 ✨ 기능 추가: PaymentService -> lecturePayment 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/facade/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/mapper/IssueCouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/mapper/LectureByStudentMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/repository/LectureByStudentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/RequestRegisterPaymentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/ResponseRegisterPaymentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
Labels: enhancement

#154 ✨ 기능 추가 : 강의 코드에 해당하는 결제 금액을 합산 쿼리 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureDetailDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/Lecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/domain/dto/LectureByStudentDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/domain/entity/LectureByStudent.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/mapper/LectureByStudentMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/repository/LectureByStudentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/dto/PaymentDetailDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
Labels: enhancement

#155 ✨ 기능 추가 : LectureService <=> LectureFacade 코드 리팩 토링 및 DTO 통합 반환 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/facade/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseFindLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java
Labels: enhancement

#157 feat(#156): 강의 삭제 시 학생 강의에서 삭제 기능 및 순환참조 해결
  LearnsMate/src/main/java/intbyte4/learnsmate/facade/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/domain/entity/LectureByStudent.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/repository/LectureByStudentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java
Labels: bug, enhancement

#158 ✨ 기능 추가 : PaymentFacade 전체 조회 및 단건조회 PaymentDetailDTO 반환 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/facade/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/facade/PaymentFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/dto/PaymentDetailDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/ResponseFindPaymentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/mapper/PaymentMapper.java
Labels: enhancement

#159 결제 전체, 단 건 조회 기능 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/facade/PaymentFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
Labels: fix

#162 git-action 적용
  .github/workflows/deploy.yml
  LearnsMate/.gitignore
  LearnsMate/gradle/wrapper/gradle-wrapper.jar
  LearnsMate/gradle/wrapper/gradle-wrapper.properties
  LearnsMate/gradlew
  LearnsMate/gradlew.bat
  LearnsMate/src/main/resources/application.yml
Labels: enhancement

#164 ✨ 기능 추가: CampaignService -> registerCampaign 예외처리 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
Labels: enhancement, fix

#166 feat(#165) - Querydsl 활용한 조회 repository 코드 리팩토링
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java
Labels: fix

#169 ✨ 기능 추가 / 수정: 회원 상세조회 메서드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/request/RequestBlacklistVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseBlacklistVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindReportVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindReservedBlacklistOneVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindReservedStudentBlacklistVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindReservedTutorBlacklistVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/FindSingleStudentDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/FindSingleTutorDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/MemberFilterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/MemberRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestEditMemberVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseFindStudentDetailVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseFindTutorDetailVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/domain/vo/request/RequestReportVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/domain/vo/response/ResponseFindReportVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/domain/vo/response/ResponseReportVO.java
Labels: bug, enhancement, fix

#172 ✨ 기능 추가 / 수정: 학생, 강사 필터링추가
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberFilterRequestDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestFilterStudentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestFilterTutorVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: enhancement, fix

#175 ✨ 기능 추가 : 강의별 계약과정이 강의 코드가 7개 라면 강의컬럼의 승인여부 true로 변환 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/controller/CommentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/repository/CommentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/service/CommentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/comment/service/CommentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/repository/ContractProcessRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/service/ContractProcessService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/service/ContractProcessServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/Lecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/request/RequestRegisterLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseRegisterLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/enums/LectureLevelEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/video_by_lecture/service/VideoByLectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/video_by_lecture/service/VideoByLectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/video_by_lecture/service/VideoByLectureServiceImpl.java
Labels: enhancement

#176 🔥 코드 수정: CampaignRepositoryCustom -> searchBy 파라미터 Entity에서 DTO 변경
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/config/QuerydslConfig.java
Labels: fix

#170 ELB에 배포
  .github/workflows/deploy.yml
  LearnsMate/.ebextensions/01-app-start.config
  LearnsMate/.platform/nginx.conf
  LearnsMate/Procfile
  LearnsMate/build.gradle
Labels: enhancement

#177 헬스 체크를 위해 추가
  .github/workflows/deploy.yml
  LearnsMate/.platform/nginx.conf
  LearnsMate/build.gradle
  LearnsMate/gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#181 feat(#180): 필터 적용한 강의 조회 기능
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/request/RequestLectureFilterVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepositoryImpl.java
Labels: enhancement

#182 ELB 하나 더 추가해서 블루그린 배포 추가
  .github/workflows/deploy.yml
Labels: enhancement

#185 ✨ 기능 추가: VOC 필터링 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryImpl.java
Labels: enhancement

#186 ✨ 기능 추가 : 강의와 카테고리 간 관계 업데이트 메서드 기능 Contoller 기능 추가
  LearnsMate/build.gradle
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureDetailDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/Lecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/LectureLevelEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/request/RequestEditLectureInfoVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/request/RequestLectureFilterVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/request/RequestRegisterLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseEditLectureInfoVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseFindLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseRegisterLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseRemoveLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/enums/LectureCategoryEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/enums/LectureLevelEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category/domain/entity/LectureCategory.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category/domain/entity/LectureCategoryEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category/mapper/LectureCategoryMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/mapper/LectureCategoryByLectureMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_video_by_student/domain/entity/LectureVideoByStudent.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_video_by_student/domain/entity/LectureVideoByStudentId.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/dto/PaymentDetailDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/RequestRegisterLecturePaymentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/ResponseFindPaymentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/service/PreferredTopicsService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/video_by_lecture/domain/entity/VideoByLecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/video_by_lecture/service/VideoByLectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/video_by_lecture/service/VideoByLectureServiceImpl.java
Labels: enhancement

#187 VOC 필터링 서비스, 컨트롤러 코드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
Labels: enhancement

#189 ♻️ 코드 수정: PaymentService -> lecturePayment 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/RequestRegisterPaymentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
Labels: fix

#190 feat(#151 #160 ): 결제 정보 등록 기능 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/RequestRegisterPaymentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/mapper/PaymentMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
Labels: enhancement, fix

#192 ✨ 기능 추가: VOCService -> countVOCByCategory 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/response/ResponseCountByCategoryVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VocCategoryService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VocCategoryServiceImpl.java
Labels: enhancement

#195 ✨ 기능 수정: VOCService -> countVOCByCategory 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/reqeust/RequestCountByCategoryVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
Labels: fix

#198 ♻️ 코드 수정: 직원 쿠폰 등록 시 couponCategory를 enum으로 사용하도록 로직 수정
  LearnsMate/build.gradle
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/AdminCouponRegisterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/domain/dto/CouponCategoryEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category/domain/entity/LectureCategoryEnum.java
Labels: fix

#199 VOC 퍼사드 추가로 인한 VOC 관련 코드 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/RequestRegisterPaymentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/VOC.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/response/ResponseFindVOCVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VOCMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/domain/VOCCategory.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/domain/dto/VOCCategoryDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/mapper/VOCCategoryMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/repository/VOCCategoryRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VOCCategoryService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VOCCategoryServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VocCategoryService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VocCategoryServiceImpl.java
Labels: enhancement, fix

#202 feat(#200): 발급된 쿠폰 조회
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/dto/AllIssuedCouponDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/vo/request/IssueCouponFilterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/CustomIssueCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/CustomIssueCouponRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
Labels: enhancement

#203 ✨ 기능 수정 : WebConfig 수정, VOC api cors 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/WebConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: enhancement

#204 ✨ 기능 수정 : deploy.yml 수정
  .github/workflows/deploy.yml
Labels: enhancement

#208 ✨기능 추가/수정: webSecurity 로그인 처리 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/request/RequestLoginVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/repository/AdminRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/AuthenticationFilter.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: enhancement

#209 계약 관련 테이블 명 수정, VOC 컬럼 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/controller/ContractStatusController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/domain/dto/ContractStatusDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/domain/entity/ContractStatus.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/domain/vo/request/ResponseRegisterContractStatusVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/domain/vo/response/RequestRegisterContractStatusVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/domain/vo/response/ResponseFindContractStatusVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/mapper/ContractStatusMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/repository/ContractStatusRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/service/ContractStatusService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/service/ContractStatusServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/controller/ContractProcessController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/mapper/ContractProcessMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/repository/ContractProcessRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/service/ContractProcessService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/VOC.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/dto/VOCDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/request/RequestCountByCategoryVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/response/ResponseFindVOCVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VOCMapper.java
Labels: fix

#210 ✨기능 추가/수정: 멤버 필터링 연결 완료
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberFilterRequestDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestFilterStudentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestFilterTutorVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: bug, enhancement

#211 ♻️ 코드 수정: admin, tutor 조회 시 발생하는 null pointer exception 해결
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
  LearnsMate/src/test/java/intbyte4/learnsmate/LearnsMateApplicationTests.java
Labels: bug

#213 ✨ 기능 추가: FindAllCampaignDTO 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/FindAllCampaignDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/entity/Campaign.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: enhancement, fix

#214 VOC 관련 로직 변경, 자료형 변경, Config 패키지 이동
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/GptConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/QuerydslConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/VOC.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/dto/VOCDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/response/ResponseFindVOCVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VOCMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/dto/VOCAnswerDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestRegisterVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseFindVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseRegisterVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/repository/VOCAnswerRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VOCCategoryServiceImpl.java
Labels: fix

#215 ✨기능 추가/수정: 학생, 강사 전체조회 필터링, 강사 단건조회
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestFilterMembertVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestFilterStudentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/video_by_lecture/repository/VideoByLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/video_by_lecture/service/VideoByLectureFacade.java
Labels: enhancement, fix

#216 voc 전체 조회 시, 필터링 시 페이지네이션 관련 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/dto/VOCFilterRequestDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/dto/VOCPageResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/request/RequestFilterVOCVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VOCMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
Labels: enhancement, fix

#219 멤버 페이지네이션 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberPageResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: enhancement

#220 ♻️ 코드 수정 : 쿠폰 조회 및 필터링 로직 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/CouponFilterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponFilterResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponFindResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/service/CouponCategoryServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: fix

#222 유저 전체 조회 offset, cursor 방식 추가 및 기간 별 카테고리 별 학생들이 구매한 강의 비율 구하는 서비스 코드 추가 (특정 기간 선택 가능)
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/CategoryCountDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/entity/Member.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/pagination/MemberPageResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/pagination/MemberPageResponseWithGraph.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/CategoryRatioFilterRequest.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/CategoryRatioResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: enhancement, fix

#223 VOC 카테고리 별 개수 구하는 API 추가 및 특정 기간으로 필터링 API 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/dto/VOCCategoryCountDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/request/VOCCategoryRatioFilterRequest.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
Labels: enhancement

#224 결제 전년도 데이터와 함께 월별로 비교 및 전체 조회 api 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/dto/PaymentMonthlyRevenueDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/PaymentPageResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/repository/PaymentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentFacade.java
Labels: enhancement

#227 ✨ 기능 수정: registerUserPerCampaign수정
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignPageResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/entity/Campaign.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestFindCampaignByConditionVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestFindCampaignCouponVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestFindCampaignStudentVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestRegisterCampaignVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignByConditionVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/mapper/CouponCategoryMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/service/CouponCategoryService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/service/CouponCategoryServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/service/CouponByCampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/userpercampaign/repository/UserPerCampaignRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/userpercampaign/service/UserPerCampaignServiceImpl.java
Labels: enhancement, fix

#228 VOC 액셀 다운로드할 때 컬럼 순서 적용 추가 및 필터링 적용
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/dto/VOCFilterRequestDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
Labels: enhancement, fix

#229 voc 답변 등록, 수정 api 프론트엔드 연동 완료
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/response/ResponseFindVOCVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VOCMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/controller/VOCAnswerController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestRegisterVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseRegisterVOCAnswerVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/mapper/VOCAnswerMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
Labels: enhancement, fix

#231 ✨ 기능 추가 : lecture 전체 조회 데이터 확인, 필터링 기능 프론트엔드 연동 확인
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/LectureLevelEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/LecturePageInfo.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseFindLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/pagination/LectureCursorPaginationResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/LectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category/domain/entity/LectureCategoryEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
Labels: enhancement, fix

#230 ♻️ 코드 수정 : 발급된 쿠폰 전체 조회 로직 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/repository/CouponByLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/service/CouponByLectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/service/CouponByLectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/dto/AllIssuedCouponDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/vo/response/AllIssuedCouponResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: fix

#235 lecture 전체 조회 데이터 확인, 필터링 기능 수정 및 단 건 조회 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/request/RequestLectureFilterVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/LecturePageInfo.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/pagination/LectureCursorPaginationResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/pagination/LecturePaginationResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/LectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java
Labels: enhancement, fix

#236 ✨ 기능 추가 / 수정: 회원 상세조회
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/dto/BlacklistFilterRequestDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/pagination/BlacklistPageResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/request/RequestFilterBlacklistMemberVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindBlacklistVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/mapper/BlacklistMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/FindSingleStudentDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
Labels: enhancement

#237 lecture 월별 데이터 조회 관련 데이터 + 필터링 기능 추가, 단 건 조회 시 구매 전환율 데이터 특정 기간 필터링 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureStatsFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/MonthlyLectureFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/LectureStatsVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseFindLectureDetailVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/LectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/repository/PaymentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
Labels: enhancement, fix

#239 ✨ 기능 추가 / 수정: 회원 엑셀 다운로드 완료
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/FindSingleStudentDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseFindMemberVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseFindStudentDetailVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: enhancement

#240 ✨기능 추가: 블랙리스트 엑셀 다운르도, 학생 엑셀 업로드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/domain/entity/LectureCategoryByLecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_video_by_student/service/LectureVideoByStudentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/login_history/domain/entity/LoginHistory.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/entity/Member.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/entity/PreferredTopics.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/domain/entity/Report.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: enhancement

#241 ✨기능 추가: 회원 카테고리별 학생 수 분석 데이터 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/CategoryStatDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
Labels: enhancement

#244 ✨ 기능 추가: MemberExcelService -> importTargetStudentFromExcel 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/FindCampaignDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberExcelService.java
Labels: enhancement

#249 ✨기능 추가: CampaignTemplateService -> findCampaignTemplateListByFilter 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestFindCampaignByFilterVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignByFilterVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/controller/CampaignTemplateController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/dto/CampaignTemplateFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/dto/CampaignTemplatePageResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/vo/request/RequestFindCampaignTemplateByFilterVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/vo/response/ResponseFindCampaignTemplateByFilterVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/mapper/CampaignTemplateMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
Labels: enhancement

#251 ✨기능 추가: 회원 로그인 컨트롤러 구현
  LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestLoginVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
Labels: enhancement

#253 ♻️코드 수정: CampaignTemplateController ->getTemplate 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/controller/CampaignTemplateController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/dto/FindCampaignTemplateDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/mapper/CampaignTemplateMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
Labels: enhancement, fix

#254 ✨기능 추가: WebSecurity HttpSecurity 설정 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: enhancement

#259 ✨ 기능 추가 :GET /admin/status 요청을 통해 로그인 상태를 확인하고 이름과 권한 담는 Controller 기능추가
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/AuthenticationFilter.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/JwtFilter.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: enhancement

#261 ✨ 기능 추가 : 직원 로그아웃 Controller 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: enhancement

#266 ✨ 기능 추가 : 직원 사번, 부서 정보 추출 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/AuthenticationFilter.java
Labels: enhancement

#267 voc AI 주차 별 저장된 데이터를 보기 위한 getAnalysisByDate 추가 및 VOC 전체 조회 시 생성일 기준 정렬 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCAiController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCAiService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/controller/VOCAnswerController.java
Labels: enhancement, fix

#269 ✨기능 추가: CampaignTemplateExcelController추가
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/controller/CampaignTemplateExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/mapper/CampaignTemplateMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepositoryCustom.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
Labels: enhancement

#270 ✨기능 추가: member, blacklist 조회시 code DESC로 하게 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java
Labels: enhancement

#271 ✨기능 추가: 엑셀 컬럼 지정 다운로드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberFilterRequestDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberExcelService.java
Labels: enhancement

#272 ✨기능 추가: 엑셀 컬럼 지정 다운로드 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberExcelService.java
Labels: enhancement

#273 ✨기능 추가: 블랙리스트 admin 찾아오는 코드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
Labels: enhancement, fix

#276 ♻️ 코드 수정 : 직원 쿠폰 등록 로직 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/RegisterCouponDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/AdminCouponRegisterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/LectureRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/domain/CouponByLecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/domain/dto/CouponCategoryEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/repository/CouponCategoryRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/service/CouponCategoryService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/service/CouponCategoryServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/Lecture.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/LectureLevelEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseFindLectureVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java
Labels: fix

#277 ♻️코드 수정: exportCampaignToExcel 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/controller/CampaignTemplateExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/dto/CampaignTemplateFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateExcelService.java
Labels: fix

#278 ✨ 기능 추가 : AdminEmailVerificationVO 이메일에 따른 사번 검증 VO 기능 추가
  LearnsMate/build.gradle
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/dto/ResponseEmailDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/entity/Admin.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/request/AdminEmailVerificationVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/request/EmailVerificationVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/request/RequestResetPasswordVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/response/ResponseEmailMessageVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/EmailService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/EmailConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/RedisConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/AuthenticationFilter.java
Labels: enhancement

#279 ✨♻️기능 추가, 수정, 코드 수정: 쿠폰 컨트롤러 파라미터 수정 및 쿠폰 발급 서비스 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/AdminCouponEditRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/TutorCouponEditRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/TutorCouponRegisterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/TutorCouponEditResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
Labels: bug, enhancement, fix

#280 ✨기능 추가: 쿠폰 관련 자잘한 비어있는 부분 추가 및 쓸데없는 파라미터 제거
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/AdminCouponRegisterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/TutorCouponRegisterRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/AdminCouponEditResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponRegisterResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
Labels: enhancement

#282 ✨ 기능 추가 :RedisService logout시 쿠키 삭제 및 redis 삭제 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/RedisService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/AuthenticationFilter.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/JwtFilter.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: enhancement

#286 ✨ 기능 추가 : redis 리프레시 토큰 및 엑세스토큰 영구 삭제 기능 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/TokenController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/RedisService.java
Labels: bug, enhancement, fix

#287 ✨기능 추가: 쿠폰 조회, 필터링 조회 offset 페이지네이션 적용, 쿠폰 엑셀 업로드 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/pagination/CouponPageResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/report/controller/ReportController.java
Labels: enhancement

#289 ✨기능 추가: BatchConfig 추가
  LearnsMate/build.gradle
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/batch/CampaignIssueCouponProcessor.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/batch/CampaignIssueCouponReader.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/batch/CampaignIssueCouponWriter.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/BatchConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponFindResponseVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/IssueCoupon.java
Labels: enhancement

#290 Lecture 단 건 조회 시 - 그래프 데이터 관련 기능 수정 (전체, 카테고리 별, 단 건 데이터)
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/LectureStatsVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseFindLectureDetailVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/LectureRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category/service/LectureCategoryService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category/service/LectureCategoryServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/PaymentPageResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/repository/PaymentRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: enhancement, fix

#291 ♻️ 코드 수정 : 쿠폰 수정 시 날짜 db에 저장되도록 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/AdminCouponEditRequestVO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: bug, fix

#293 github-action 무중단 배포 오류로 인한 수정
  .github/workflows/deploy.yml
  LearnsMate/.platform/nginx.conf
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/EmailConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: fix

#296 ♻️ 코드 수정 : 쿠폰 필터 조건 적용되도록 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponExcelService.java
Labels: fix

#298 ♻️코드 수정: scheduleCampaigns 수정
  LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/EmailConfig.java
  LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java
Labels: fix

#301 ✨기능 추가: 발급쿠폰 엑셀 다운로드, 발급 쿠폰 페이지네이션 추가
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponExcelController.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/dto/IssuedCouponFilterDTO.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/pagination/IssueCouponPageResponse.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/CustomIssueCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/CustomIssueCouponRepositoryImpl.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponExcelService.java
  LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponFacade.java
Labels: enhancement, fix

#302 ✨ 기능 수정 : nginx.conf 수정
  .github/workflows/deploy.yml
  LearnsMate/.platform/nginx.conf
  LearnsMate/src/main/java/intbyte4/learnsmate/security/JwtFilter.java
  LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
Labels: fix
